import { Poppins } from "next/font/google";
import "./globals.css";
import SideBar from "@/components/Global/SideBar";

const poppins = Poppins({
  subsets: ["latin"],
  weight: ["400", "500", "600", "700", "800", "900"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <SideBar/>
      <body className={poppins.className}>{children}</body>
    </html>
  );
}
